name: Web UI Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-web-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Give permission to gradlew
        run: chmod +x gradlew

      - name: Run automation test
        run: ./gradlew clean test

      - name: Show directory listing (debug)
        run: |
          echo "Checking build folder:"
          ls -R build

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            build/reports/tests/test/
            build/cucumber-reports/