name: Web & API Test Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-web-tests:
    name: Run Web UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Grant permission to execute Gradle
        run: chmod +x ./gradlew

      - name: Run Web UI Tests
        run: ./gradlew test -Dcucumber.filter.tags="@web"

      - name: Upload Web Reports (HTML + JSON)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-report
          path: |
            target/web/cucumber-html-report.html
            target/web/cucumber-report.json

  run-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: run-web-tests  # optional: only if API should run after Web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant permission to execute Gradle
        run: chmod +x ./gradlew

      - name: Run API Tests
        run: ./gradlew test -Dcucumber.filter.tags="@api"

      - name: Upload API Reports (HTML + JSON)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-report
          path: |
            target/api/cucumber-html-report.html
            target/api/cucumber-report.json